# -*- coding: utf-8 -*-
"""assignment4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-p1nx78BNk5g_sk-Vr2_OqfHBEqS1o5
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
df=pd.read_csv('data.csv')

df.head()

df.isnull().sum()

df.info
df.sample(5)

df.describe()

df.groupby("city")[["price"]].sum()

average_price = df['price'].mean()
f"The average price is: {average_price:.2f}"

max_sale_percentage = df['price'].max()
print(f"The maximum sales percentage is: {max_sale_percentage:.2f}%")
print(f"The maximum sales percentage is: {max_sale_percentage:.2f}%")
df.columns

floor_per_yr_built = df['yr_built'].value_counts()

floor_counts = df['floors'].value_counts()

floor_percentage = (floor_counts / len(df)) * 100

floor_percentage_df = floor_percentage.reset_index()
floor_percentage_df.columns = ['Floors', 'Percentage']

